version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: roadXPertDB
    user: root
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_USER: "Developer"   
      MSSQL_PASSWORD: "Devel0per!"
    ports:
      - "1433:1433"
    volumes:
      - ./DB:/var/opt/mssql/data

# to run the container
# docker-compose up -d